### ISSUE TITLE
Possible problem with tags containing a comma

### ISSUE THREAD

**Issue by PeteVox** [goldsky/SmartTag#19]
Apologies is this is due to incorrect set up of input properties (in which case please let me know). 

We're using several SmartTags in a development system where some tag values contain commas. When saving a resource containing a 'comma-based' tag (let's call this R1), the smarttag value is correctly added to the 'smarttag_tags' table along with association in table 'smarttag_tagresources'. All good so far. The document resource (R1) also correctly shows the comma-based tag in the manager interface after screen refreshes. All good.

Problem appears after editing another resource document (any) and then reloading the original R1 resource. No comma-based tags seem to appear in the manager interface - though any tags NOT containing commas do. If resource R1 is then edited and saved (any field - content, pagetitle etc.), then association to those non-displayed comma-based tags is lost in table 'smarttag_tagresources'. 

We fixed the problem in our dev system by editing file 'modx_core/components/smarttag/elements/tv/mgr/input/tpl/smarttag.tpl'. We changed line 37 from ',valueDelimiter: ","' to ',valueDelimiter: "|"'.

Again, if this is related to input properties not being correctly set up, then apologies. Otherwise, can we suggest some kind of permanent fix in a future release?

We're currently running version 1.0.0-rc2.

Many thanks for a great component goldsky. Really is a big help for our particular system requirements.

**Comment by goldsky** [comment]
I'm closing this issue.
If you have more thought, please post back.
