### ISSUE TITLE
Tags are transliterated from cyrillic to latin

### ISSUE THREAD

**Issue by kivils** [goldsky/SmartTag#22]
Hi!
SmartTag version 1.0.1 pl.
When I add new value in TV in cyrilic, it automatically transliterated to latin.
For example, "новости" - "novosti".
![image](https://cloud.githubusercontent.com/assets/4233899/6037086/12888dd8-ac71-11e4-9a7b-4b1dbef7f9ba.png)
When I hit Enter, tag is converted to
![image](https://cloud.githubusercontent.com/assets/4233899/6037103/312ec874-ac71-11e4-8f97-96b35a91790c.png)

I need my tags in cyrillics.
For transliterating aliases I use "translit" extra from modx.com - http://modx.com/extras/package/translit.

I've got another site, SmartTag version 1.0.0 beta 6, I use "translit" extra too - and tags is saved in cyrillic, no problem.

What is wrong? Thanks for any advise

**Comment by goldsky** [comment]
there were an upgrade to replace that.
And it's using alias cleaner as well.
https://github.com/goldsky/SmartTag/blob/master/core/components/smarttag/processors/mgr/tags/filter.class.php#L34
Have you installed translit extra into this particular website?

**Comment by kivils** [comment]
Thanks for reply!
I've installed translit extra and 'SmartTag v.1.0.0 beta 6' into one of my sites (about 6 month ago), and SmartTag works perfect.
And I've installed translit extra and 'SmartTag v.1.0.1 pl' into another site, and I have this problem on this site.

It seems, that I've isntalled the latest version of SmartTag on my second site. SmartTag/core/components/smarttag/processors/mgr/tags/filter.class.php - this file on my site is the same as this https://github.com/goldsky/SmartTag/blob/master/core/components/smarttag/processors/mgr/tags/filter.class.php#L34

PS: I converted TV "auto tag" to "SmartTag" in CMP, and then tried to add new cyrillic value here - and I've got transliterated value.
PPS: I had to alter tables in my database to UTF-8, otherwise when I convert Autotag to Smarttag I've got "??????" in my DB table instead of cyrillic value of tag.

**Comment by kivils** [comment]
Thank you, Rico!

**Comment by goldsky** [comment]
Yw, kivils.

Still, I am expecting other feedback regarding to cyrillic tags.

**Comment by kivils** [comment]
When I set the option 'Use filter' to 'No', cyrillic tags saved in cyrillic, not transliterated. That's exactly what I needed. Thank you very much for this update! You solved my problem!
