### ISSUE TITLE
Tags are being forced to lowercase.

### ISSUE THREAD

**Issue by BigBlockStudios** [goldsky/SmartTag#24]
Upon entering a new tag "Sedan" it will be forced to lowercase likewise "GMC" shows up as "gmc" in the smarttag table.

**Comment by goldsky** [comment]
I had problem with the uppercase on Ext.ux.form.SuperBoxSelect sometimes ago.
But I'll add an option to disable it.

**Comment by BigBlockStudios** [comment]
This is still happening after updating to 1.0.2, It looks like the javascript is converting the case before the tag gets inserted into the database ~ I've been through it and don't see where its getting converted & wondering if it's modx extjs that's doing it. 

Process is:
- type in a tag "Coupe" 
- if it's not found in the database, no type ahead results are found
- hit enter & tag is reformatted as "coupe" 
- check database tables, site_tmplvar_contentvalues & smarttag_tags - "Coupe" or "coupe" not there yet
- "coupe" will appear in both tables when I save the resource.

Also, just discovered:
I have an entry "Zastava" in both tables of the database. Type ahead will not find this tag if typed in in either case.

**Comment by goldsky** [comment]
have you set "smarttag.use_filter" in System Settings to "no"?

**Comment by BigBlockStudios** [comment]
I had not.  honestly, I just downloaded the update and tested, I missed anywhere it said to update that [I should have looked closer]

I just changed that and it appears to be working now :) 

Thanks for your help and prompt updates.  Very greatly appreciated. 

-sean

**Comment by goldsky** [comment]
yw
