### ISSUE TITLE
does not return unique resources count, but return multiple count on same resource with different tv and same tags

### ISSUE THREAD

**Issue by u007** [goldsky/SmartTag#26]
if a resource have multiple tv and few tv having same tags,
it will return the multiple rows,
suggested count to add in distinct(modResource.id)

**Comment by goldsky** [comment]
for what snippet call?

**Comment by u007** [comment]
smarttagTags

**Comment by goldsky** [comment]
The complete snippet usage, please

**Comment by goldsky** [comment]
you need to define ```
&tvNames=`your_tv_name(s, comma delimited of multiple TVs if any)`
``` to set the scope.
