### ISSUE TITLE
count does not honor tvnames

### ISSUE THREAD

**Issue by u007** [goldsky/SmartTag#27]
count of resources does not honor tvnames passed in
the subqueries need to support this within it.

(empty($tvNames) ? '': 'AND smarttagTagresources.tmplvar_id =TemplateVar.id') .

**Comment by goldsky** [comment]
for what snippet call?

**Comment by goldsky** [comment]
`&tvNames` is only applied if either `&docIds` or `&parentIds` is used.
I've updated the doc as well, http://rtfm.modx.com/extras/revo/smarttag

Sorry for the confusion.

**Comment by u007** [comment]
hi,
can you reopen this?
as we did pass in parentIds

**Comment by u007** [comment]
the issue is tvnames was applied to tags,
but the count wasnt...

**Comment by goldsky** [comment]
I can't help you further if you don't share the complete snippet call, its usage with all the parameters you're using.

**Comment by u007** [comment]
[[!smarttagTags?
                    &parentIds=`[[*id]]`
                    &includeHiddenDocs=`1`
                    &tplWrapper=`@code:[[+smarttag.tags]]`
                    &tplItem=`SupplierProfileItem`
                    &tvNames=`product-keywords`
                ]]
