### ISSUE TITLE
A lot of tags (>300) makes SmartTag autocomplete stop working in manager

### ISSUE THREAD

**Issue by vierkantemeter** [goldsky/SmartTag#29]
I'm having more than 300 tags (not ideal, I know), and because of this tremendous amount of tags, the auto-suggest function of SmartTag is not working. See in action below:

![voila_capture 2015-07-17_01-11-47_pm](https://cloud.githubusercontent.com/assets/487567/8746033/9faac5de-2c85-11e5-92ef-f9461c0f496c.gif)

MODX 2.3.4
SmartTag 1.0.3

**Comment by goldsky** [comment]
Originally, it only gets the tags that are created by that particular TV, not cross TVs.
I'll add an option to make it enabled.

**Comment by goldsky** [comment]
updated on git, will be available on next release.
