### ISSUE TITLE
A lot of tags (>300) breaks SmartTag manager 

### ISSUE THREAD

**Issue by vierkantemeter** [goldsky/SmartTag#30]
I have more than 300 tags, and viewing them in the tag manager breaks paging. See in action:

![voila_capture 2015-07-17_01-20-11_pm](https://cloud.githubusercontent.com/assets/487567/8746142/bd152cee-2c86-11e5-8e54-1532fe8f93ab.jpg)

MODX 2.3.5
SmartTag 1.0.3

**Comment by goldsky** [comment]
Click "Load more"?

**Comment by vierkantemeter** [comment]
Then, the 'Load more" button will move down and the grey area will expand, but there aren't more tags shown.

**Comment by goldsky** [comment]
Mind to share the mgr access?
goldsky@virtudraft.com, please

**Comment by vierkantemeter** [comment]
Sure thing. Just send you login details via e-mail!

**Comment by goldsky** [comment]
Found the problem regarding to modx 2.3.x's new styling.
I'll make an update.

**Comment by goldsky** [comment]
fixed

**Comment by vierkantemeter** [comment]
Thanks!

**Comment by goldsky** [comment]
I'll be uploading new version for the updates, so I'm closing this issue.
