### ISSUE TITLE
Tag list on the page

### ISSUE THREAD

**Issue by luxeth** [goldsky/SmartTag#31]
Pretty strange question, but.. Am I able to put article's list of tags into the regular page? And create a page where all links to the articles will be listed, not in administration panel.

**Comment by goldsky** [comment]
Of course.
That's what smarttagTags snippet is for.
Pleas read its usage on rtfm.

**Comment by luxeth** [comment]
But.. I don't have this one. There's only "smarttagtags.wrapper" and "smarttagtags.item" in smartTag folder, and one TV for admin-panel.

**Comment by luxeth** [comment]
Ew, I found it. But when I posted [[smarttagTags]] on the template via admin-panel, there is just blank space on the site.

**Comment by goldsky** [comment]
ow?
pls check error log, and apache's error log?

**Comment by goldsky** [comment]
It works on my side. What's your snippet's call?

**Comment by luxeth** [comment]
There's no really errors. Plugin's name? I have "smarttagTags" snippet with big code. Maybe I should write something else into " [[smarttagTags]] " to call it?

**Comment by goldsky** [comment]
You need either &docIds or &parentIds parameter of the resources

http://rtfm.modx.com/extras/revo/smarttag

**Comment by luxeth** [comment]
Yes, sure I did it. This snippet works for me, but only if I use "allTags=`true`" part. But it shows me.. all tags:D
[[smarttagTags? parentIds=`10` &allTags=`false` &tvNames=`tagsTV`]]

**Comment by goldsky** [comment]
```
[[smarttagTags?
&parentIds=`10`
&tvNames=`tagsTV`
]]
```

**Comment by luxeth** [comment]
The emptiness again. It's so fun when it actually works but I think I don't did something that need to make tit works. :D

**Comment by goldsky** [comment]
try 1.0.5-pl
