### ISSUE TITLE
Same tag name from different TVs causes tag total miscount

### ISSUE THREAD

**Issue by adamwintle** [goldsky/SmartTag#33]
### Summary
When there are two different SmartTag TVs (e.g. `keywords` and `country`) and some tag names are used across both TVs, then the total counts can sometimes be wrong.

For example `keywords` has the `games, art, Indonesia` and `country` has `Indonesia`; when calling a snippet like this: 
```
[[!smarttagTags?
	&parentIds=`1`
	&limit=`50`
	&tvNames=`keywords`
]]
```
The resulting list should just show `Indonesia (1)` since this is tagged once within the `keywords` TV, however the final count is `Indonesia (2)` because it actually counts across all SmartTag TVs not just the specified TV in `&tvNames`.

### Environment
MODX version 2.4.0-pl, SmartTag 1.0.4-pl

**Comment by goldsky** [comment]
fixed https://github.com/goldsky/SmartTag/commit/acade0c05c5cf367f3b923392f1a56e0626bb637

**Comment by goldsky** [comment]
try 1.0.5-pl

**Comment by adamwintle** [comment]
:+1: You are fast! :)
