### ISSUE TITLE
Bug if using in MIGX

### ISSUE THREAD

**Issue by Artexoid** [goldsky/SmartTag#35]
Dear developers. I found exception if using extension with MIGX.

In template
~/core/components/smarttag/elements/tv/mgr/input/tpl/smarttag.tpl **line 12**
**$tv->id** can be **string type** in MIGX.

For correct work need replace

,tvId: {/literal}{$tv->id}{literal} /* replace to --> */ ,tvId: '{/literal}{$tv->id}{literal}' (**add quotes**)

**Please correction this in next release.**

Thank you very much for your extension! :-)

**Comment by goldsky** [comment]
SmartTag in MIGX?
Whats your grid's config?

**Comment by Artexoid** [comment]
1. I create SmartTag TV before ( for example with name 'tags' ).
2. I create config MIGXDB
```
            ..... 
     ],[
            'field' => 'tags',
            'caption' => 'Список тегов',
            'inputTV' => 'tags'
     ],[
            .....
```
3. After run with config this MIGX generates components to window with not standard id.

It situation brakes the javascript execution..

Maybe something i did wrong ...
